### ISSUE TITLE
Hosted documentation doesn't indicate async functions

### ISSUE THREAD

**Issue by willrogers** [dls-controls/aioca#2]
e.g. https://aioca.readthedocs.io/en/latest/api.html#aioca.caput

And yet if I build it locally the HTML does indicate async functions. Is this a Sphinx version difference?

**Comment by thomascobb** [comment]
Yes, readthedocs is on an older version of sphinx. I plan to move to GitHub.io soon...

**Comment by willrogers** [comment]
There doesn't seem to be anything here: https://dls-controls.github.io/aioca

**Comment by thomascobb** [comment]
I forgot to flick the setting in https://github.com/dls-controls/aioca/settings/pages. Then I wasted 2 hours trying to get Github Actions to do this for me in the workflow so I can put it in the template module, only to be greeted by: 
```
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-github-pages-site"
}
```
Thanks GitHub...

**Comment by willrogers** [comment]
OK, looks good now.

At least the error message was clear enough.
